### ISSUE TITLE
No direct offers found! Did they make some changes to the website? Please report @github if this happens multiple times

### ISSUE THREAD

**Issue by Tiippex** [sibalzer/primelooter#13]
Hello,

I'm getting this error quite often
![image](https://user-images.githubusercontent.com/16509128/135152699-286b7a16-e951-4525-8bd5-aa65d45a855e.png)

No direct offers found! Did they make some changes to the website? Please report @github if this happens multiple times.

By the way: Thanks for the looter. Everything else works pretty well in the supplied container :)

Tiippex

**Comment by sibalzer** [comment]
It might have to do with how the website loads. Im onto it.

**Comment by sibalzer** [comment]
Does it still appear? (I've changed the looting procedure in 4948fc5.)

**Comment by Tiippex** [comment]
Hey,

thanks for the upgrade. I'm not sure if it is related to the update but for some reason, the account detection doesn't work anymore.
![image](https://user-images.githubusercontent.com/16509128/139125936-1328d445-c6a8-47c1-a106-2615db39de09.png)

**Comment by sibalzer** [comment]
Yes, I have also noticed. No idea why Amazon does not notice the link (only with EA and Wargaming). For a fix, unfortunately, the whole bot would have to be refactored/rebuild (with its own processes for the various publisher logins). Unfortunately, I currently lack the motivation to do so, as my Prime expires and I will not extend my subscription further for now.
