### ISSUE TITLE
feature request: detect game codes and save them into a file

### ISSUE THREAD

**Issue by sibalzer** [sibalzer/primelooter#16]
Sometimes when claiming a game (e.g. star wars squadrons) we get a code for steam, origin or uplay. The code is shown in the `gms-success-modal-container`, but i don't have the html-code because the bot already claimed everything 😄 . It would be nice if somebody could provide me the code of the modal container, otherwise i must wait for new games. (but please remove personal information like name and the code)

**Comment by ankushg** [comment]
@sibalzer this month has a few:

- Control is a code for GOG
- Dragon Age Inquisition is a code for Origin

**Comment by sibalzer** [comment]
thx

closed with b55e526
