### ISSUE TITLE
Automatic Code Redemption On Gog And Origin

### ISSUE THREAD

**Issue by EnumC** [sibalzer/primelooter#21]
Feature Request:

Since these promotional keys frequently have an expiry date, it would be a great feature to have the script parse the code from the success modal, then automatically activate the code on the respective webstore. 

For example, if our GOG key is `Z6XR90XX645998XX3C`, then we can form a target URL as: https://gog.com/redeem/Z6XR90XX645998XX3C. After navigating to that URL, we can then simulate a click on the "Continue" submit button to activate the code.

If we run into any issues with ReCaptcha, open the target URL in non-headless mode and let the user click that one button to activate.

**Comment by sibalzer** [comment]
Since i don't have Prime anymore, this project is no longer maintained. Please use [srhinos fork](https://github.com/srhinos/primelooter).
